# Generated by Django 5.1.3 on 2024-12-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publicated_date',
            new_name='published_date',
        ),
    ]
